// Code generated by goctl. DO NOT EDIT.
package types

type ChatReq struct {
	Question string `json:"question" form:"question"`
}

type ChatResp struct {
	Answer string `json:"answer" form:"answer"`
}
